version: '3'

services:
  webdis:
    build: .
    ports:
      - 7379:7379
    entrypoint: /app/entrypoint.sh
    labels:
      - traefik.frontend.rule=Host:webdis.next.health
      - traefik.port=7379
    network_mode: "bridge"
